# Generated by Django 5.0.3 on 2024-03-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_created_at_alter_product_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('inn', models.PositiveBigIntegerField(verbose_name='ИНН')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Почтовый адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='preview/', verbose_name='Логотип сайта')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания (записи в БД)')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата последнего изменения (записи в БД)')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
            },
        ),
    ]
